SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT LIKE 'a%'
  AND LOWER(CITY) NOT LIKE 'e%'
  AND LOWER(CITY) NOT LIKE 'i%'
  AND LOWER(CITY) NOT LIKE 'o%'
  AND LOWER(CITY) NOT LIKE 'u%'
  AND LOWER(CITY) NOT LIKE '%a'
  AND LOWER(CITY) NOT LIKE '%e'
  AND LOWER(CITY) NOT LIKE '%i'
  AND LOWER(CITY) NOT LIKE '%o'
  AND LOWER(CITY) NOT LIKE '%u';
  
  
  
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) REGEXP '^[^aeiou].*[^aeiou]$';